name: Healthcheck

on:
  push:
    branches:
      - main

jobs:
  check-deployment:
    runs-on: ubuntu-20.04
    steps:
      - name: Ping server
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://phonebook-xlp7.onrender.com/health
